# Generated by Django 3.1.6 on 2021-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210213_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider_post',
            field=models.BooleanField(default=False),
        ),
    ]
